# Generated by Django 5.1.4 on 2025-01-21 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                help_text="Время, которое пользователь предположительно потратит на то чтобы приступить к выполнению",
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
    ]
