# Generated by Django 5.1.4 on 2025-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="day_choice",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="day_choice",
                to="habit_tracker.daychoices",
                verbose_name="Дни выполнения действия",
            ),
        ),
    ]
