# Generated by Django 5.1.4 on 2025-01-28 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_alter_habit_day_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ("owner",), "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="day_choice",
            field=models.ManyToManyField(
                blank=True,
                related_name="day_choice",
                to="habit_tracker.daychoices",
                verbose_name="Дни выполнения действия",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с другой привычкой",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habit_tracker.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
